#database properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#filter order
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2

#jwt secret token
jwt.secret=${SECRET_TOKEN:jtufud56j8f75dsg6jgi6u7g67558j9hj0phh0fu5fjhytthgygfyyyrjgutiokigjuhfgrg}

#service Registry
eureka.client.service-url.defaultZone=http://${SERVICEE_REGISTRY_HOST:localhost}:8761/register/eureka
